### ISSUE TITLE
validation fails on date fields in forms

### ISSUE THREAD

**Issue by pmdredd** [pmdredd/CourseApp#2]
Issue: Validation fails when trying to submit any form with a date field with the error: 'this value should be of type string'. This issue did not exist in the Symfony 4.4 version of the application.

Potential solution: somewhere between the Entity and the FormType for that Entity, Symfony is failing to properly covert betweem string and DateTime. Inspecting the POST information on submit (in dev tools) shows that the date is being posted properly as a string. The Symfony profiler also shows that the date is posted back as a string.

**Comment by zwarthoorn** [comment]
Good day,

I have made a pull request for you,
i was intrigued by this issue and wanted to fix it,
i hope you take it in consideration what i have build
